### ISSUE TITLE
Update to Release 0.110.4 - Platform error sensor.afvalbeheer - No module named 'rsa'

### ISSUE THREAD

**Issue by Nenodema** [pippyn/Home-Assistant-Sensor-Afvalbeheer#102]
During the upgrade check of Home Assistant 0.110.4 the upgrade checker encountered the following error:

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[07:24:17] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[07:24:18] INFO: Setup udev devices

[07:24:19] INFO: Don't worry, this temporary installation is not overwriting your current one.
[07:24:19] INFO: Installing Home Assistant: latest...
[07:24:19] INFO: Please be patient, this might take a few minutes...
[07:27:23] INFO: Installed Home Assistant 0.110.3
[07:27:23] INFO: Making a copy of your configuration for checking...
[07:27:24] INFO: Checking your configuration against this version...
[07:34:12] ERROR: The configuration check did not pass!
[07:34:12] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform error sensor.afvalbeheer - No module named 'rsa'

Successful config (partial)
[07:34:12] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Do you have any idea howto fix this? Thanks for your effort!

**Comment by pippyn** [comment]
Which install method did you use to install HA?
This is a dependency issue. Are you willing to do a test for me?
Can you replace the contents of `[your-config-folder]/custom_components/afvalbeheer/manifest.json` with this: https://raw.githubusercontent.com/pippyn/Home-Assistant-Sensor-Afvalbeheer/master/custom_components/afvalbeheer/manifest.json
Restart HA and try the upgrade checker again

**Comment by Nenodema** [comment]
I'm using the Hassio Supervisor with HACS for "Afvalbeheer".

Current content of manifest.json:

```
{
  "domain": "afvalbeheer",
  "name": "Afvalbeheer",
  "documentation": "https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer",
  "dependencies": [],
  "codeowners": ["@pippyn"],
  "requirements": []
}

```

Currently testing the upgrade with your suggested change! I will let you know the outcome..

**Comment by Nenodema** [comment]
New error:

```
[09:03:29] INFO: Don't worry, this temporary installation is not overwriting your current one.
[09:03:29] INFO: Installing Home Assistant: latest...
[09:03:29] INFO: Please be patient, this might take a few minutes...
[09:06:44] INFO: Installed Home Assistant 0.110.3
[09:06:44] INFO: Making a copy of your configuration for checking...
[09:06:44] INFO: Checking your configuration against this version...
[09:13:03] ERROR: The configuration check did not pass!
[09:13:03] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Failed config
  General Errors: 
    - Platform error sensor.afvalbeheer - No module named 'Crypto'

Successful config (partial)
[09:13:03] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.

```

**Comment by pippyn** [comment]
Can you add pycripto as a dependency to manifest.json? like so:
```
{
  "domain": "afvalbeheer",
  "name": "Afvalbeheer",
  "documentation": "https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer",
  "dependencies": [],
  "codeowners": ["@pippyn"],
  "requirements": [
    "rsa==4.0",
    "pycrypto==2.6.1"
  ]
}
```

**Comment by Nenodema** [comment]
New error:

```
[09:30:59] INFO: Don't worry, this temporary installation is not overwriting your current one.
[09:30:59] INFO: Installing Home Assistant: latest...
[09:30:59] INFO: Please be patient, this might take a few minutes...
[09:34:08] INFO: Installed Home Assistant 0.110.3
[09:34:08] INFO: Making a copy of your configuration for checking...
[09:34:08] INFO: Checking your configuration against this version...
[09:39:20] ERROR: The configuration check did not pass!
[09:39:20] ERROR: See the output below for more details.
Testing configuration at /tmp/config
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py", line 313, in recv_into
    return self.connection.recv_into(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1840, in recv_into
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.7/site-packages/OpenSSL/SSL.py", line 1663, in _raise_ssl_error
    raise SysCallError(errno, errorcode.get(errno))
OpenSSL.SSL.SysCallError: (104, 'ECONNRESET')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 425, in _error_catcher
    yield
grep: write error: Broken pipe
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

Thanks for your time btw :-)

**Comment by pippyn** [comment]
This error isn't caused by this sensor, I think. Can you try removing your config for this sensor? and try again? If the error persists, it's not the fault of this sensor.
This is some kind of ssl issue (?)

**Comment by Nenodema** [comment]
Check, it was a connection error!

```
[09:46:57] INFO: Don't worry, this temporary installation is not overwriting your current one.
[09:46:57] INFO: Installing Home Assistant: latest...
[09:46:57] INFO: Please be patient, this might take a few minutes...
[09:49:45] INFO: Installed Home Assistant 0.110.3
[09:49:45] INFO: Making a copy of your configuration for checking...
[09:49:45] INFO: Checking your configuration against this version...
[09:55:55] ERROR: The configuration check did not pass!
[09:55:55] ERROR: See the output below for more details.
Testing configuration at /tmp/config
ERROR: No matching distribution found for pycrypto==1000000000.0.0 (from -c /usr/local/lib/python3.7/site-packages/homeassistant/package_constraints.txt (line 39))
WARNING: You are using pip version 20.0.2; however, version 20.1.1 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.
Failed config
  General Errors: 
    - Platform error sensor.afvalbeheer - Requirements for afvalbeheer not found: ['pycrypto==2.6.1'].

Successful config (partial)
[09:55:55] INFO: The full output has been written to /share/check_config.txt
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by pippyn** [comment]
Can you try installing pycrypto manually in the command line?
`pip3 install pycrypto`

**Comment by pippyn** [comment]
Can you try with the following contents of manifest.json

```
{
  "domain": "afvalbeheer",
  "name": "Afvalbeheer",
  "documentation": "https://github.com/pippyn/Home-Assistant-Sensor-Afvalbeheer",
  "dependencies": [],
  "codeowners": ["@pippyn"],
  "requirements": [
    "rsa==4.0",
    "pycryptodome==3.9.7"
  ]
}
```

**Comment by Nenodema** [comment]
Check, give me 20 min!

**Comment by Nenodema** [comment]
Yeah, works! Thanks!

```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] udev.sh: executing... 
starting version 3.2.9
[15:09:08] INFO: Update udev information
[cont-init.d] udev.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[15:09:09] INFO: Setup udev devices

[15:09:10] INFO: Don't worry, this temporary installation is not overwriting your current one.
[15:09:10] INFO: Installing Home Assistant: latest...
[15:09:10] INFO: Please be patient, this might take a few minutes...
[15:12:14] INFO: Installed Home Assistant 0.110.3
[15:12:14] INFO: Making a copy of your configuration for checking...
[15:12:14] INFO: Checking your configuration against this version...
[15:19:33] INFO: Configuration check finished - no error found! :)
[cont-finish.d] executing container finish scripts...
[cont-finish.d] done.
[s6-finish] waiting for services.
[s6-finish] sending all processes the TERM signal.
[s6-finish] sending all processes the KILL signal and exiting.
```

**Comment by pippyn** [comment]
Nice! sorry for the inconvenience
