### ISSUE TITLE
Configuration with Limburg.NET stops working after a while

### ISSUE THREAD

**Issue by Stefans94** [pippyn/Home-Assistant-Sensor-Afvalbeheer#149]
When I restart home assistant the sensor is able to fetch the information from Limburg.NET, but after a few hours I receive the following error and it stops getting data:

```Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:783
First occurred: 24 september 2020 15:29:08 (1 occurrences)
Last logged: 24 september 2020 15:29:08

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 429, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 796, in update
    response = await self.hass.async_add_executor_job(self.__get_data)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 783, in __get_data
    data = data + month_json['events']
KeyError: 'events'
````

**Comment by pippyn** [comment]
Do you still have this issue? Do you have an address for me to test with?

**Comment by Stefans94** [comment]
There might have been an issue with limburg.net itself because it seems to be working now.
