### ISSUE TITLE
RD4 not working

### ISSUE THREAD

**Issue by DavidVankan** [pippyn/Home-Assistant-Sensor-Afvalbeheer#200]
i can see de sensor vandaag en morgen.
GFT,Restafval,Papier,Plastic are all unknown.

using the RD4

**Comment by pippyn** [comment]
Some more information would be helpful:
- Did it work before?
- Any errors in your log?
- What's your config?
- Please provide an address in your neighborhood

**Comment by Gebruikertje** [comment]
Hi Pippyn,

I got the same problem, I can see the sensors, but they all got no data. It worked before, I'm running version v4.7.14 of Afvalbeheer.

My Config:

- platform: afvalbeheer
  wastecollector: RD4
  resources:
    - restafval
    - gft
    - papier
    - pmd
    
  postcode: 6466AM
  streetnumber: 106
  upcomingsensor: 1
  dateformat: '%d-%m-%Y'
  dateonly: 0
  dateobject: 0
  name: 'RD4'
  nameprefix: 0
  builtinicons: 1
  disableicons: 0
  dutch: 1

In the log I see the following message:

2021-02-22 13:56:30 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 481, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1063, in update
    response = r.json()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())

**Comment by pippyn** [comment]
This config is working fine for me on the latest version of HA and the latest version of the sensor. Maybe a firewall issue?

**Comment by Marclinh0** [comment]
Hello Pippyn
I have  the same configuration as GEBRUIKERTJE although with my Own postal code and Streetnumber
And also the same problem
![image](https://user-images.githubusercontent.com/78760570/108850914-29d8cf00-75e4-11eb-85b5-a6aa7d1ba5bd.png)

**Comment by Marclinh0** [comment]
And the same error message in the log

2021-02-23 14:37:42 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/config/custom_components/afvalbeheer/sensor.py", line 427, in async_update
await self.collector.update()
File "/config/custom_components/afvalbeheer/sensor.py", line 1009, in update
response = r.json()
File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
return complexjson.loads(self.text, **kwargs)
File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
return _default_decoder.decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
obj, end = self.raw_decode(s)
File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Gebruikertje** [comment]
Ik heb vanaf de HA machine geprobeerd een wget te doen op https://rd4.syzygy.eu/ en dan krijg ik een error 429 - Too Many Requests.

**Comment by pippyn** [comment]
The 429 error means that the sensor is trying to many times to get the information. You could try and set the update frequentie to a higher number (line 63 in sensor.py), maybe 10 hours? Reboot HA and wait a couple of days to see if this change works. If so I will make the value available in the config.

**Comment by Gebruikertje** [comment]
I've changed the update frequency to 12 hours, at first I didn't get any information on garbage collection. But now, after a few days, I finally see the wanted data.
