### ISSUE TITLE
RecycleApp unhandled error on location lookup

### ISSUE THREAD

**Issue by Tommatheussen** [pippyn/Home-Assistant-Sensor-Afvalbeheer#218]
Sometimes the location lookup seems to fail for the RecycleApp API. I then get the following log in my logs and all my sensors report unavailable (if it happened on startup).
```
Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:1105
First occurred: 13:00:55 (1 occurrences)
Last logged: 13:00:55

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 436, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1136, in update
    await self.hass.async_add_executor_job(self.__get_location_ids)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1105, in __get_location_ids
    self.postcode_id = response.json()['items'][0]['id']
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 3 - line 1 column 5 (char 2 - 4)
```
I have had this a couple of times and it seems the API doesn't return correct info for the location query, so I though I would log the result that the call returns. For this, I have added `_LOGGER.warning(response.text)` at line 1104 in an attempt to capture what the API returns, this logged the following:
```
{}{}
```

I realise this isn't much info to go by, I'm not experienced enough in python for proper logging. I'm happy to add different logging if you want more information, just let me know what needs to be done :D

**Comment by ghluhi** [comment]
I'm also seeing the same error. Always failure. No information is captured.

```
Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:1104
First occurred: 10:07:48 (1 occurrences)
Last logged: 10:07:48

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 436, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1135, in update
    await self.hass.async_add_executor_job(self.__get_location_ids)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1104, in __get_location_ids
    self.postcode_id = response.json()['items'][0]['id']
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 3 - line 1 column 5 (char 2 - 4)
```
Version installed is v4.7.19 (HACS).

**Comment by Tommatheussen** [comment]
I usually see it happen after frequent restarts as well, maybe it's an attempt at rate limiting, seeing as the lookup happens each time that HA starts

**Comment by pippyn** [comment]
The recycleApp api has had some issues in the last couple of weeks. It all seems resolved now. I'll close this issue.
