### ISSUE TITLE
RecyleApp wastecollector not working on .19 or .20

### ISSUE THREAD

**Issue by jeroomdm** [pippyn/Home-Assistant-Sensor-Afvalbeheer#227]
Last working version for me is 4.7.18
If i upgrade to .19 or .20 i get the sensors all as unknown
I use RecyleApp as wastecollector.
After the update to .19 or .20 i get the next error:
`2021-04-30 08:06:06 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 437, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 1136, in update
    await self.hass.async_add_executor_job(self.__get_location_ids)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 1105, in __get_location_ids
    self.postcode_id = response.json()['items'][0]['id']
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/site-packages/simplejson/decoder.py", line 373, in decode
    raise JSONDecodeError("Extra data", s, end, len(s))
simplejson.errors.JSONDecodeError: Extra data: line 1 column 3 - line 1 column 5 (char 2 - 4)`

If i rollback to .18 it works perfectly

**Comment by pippyn** [comment]
I'm sorry to hear that!
what config do you use?

**Comment by jeroomdm** [comment]
- platform: afvalbeheer
    wastecollector: RecycleApp
    resources:
      - grofvuil
      - papier
      - pmd
      - restafval
      - textiel
    printwastetypes: 0
    postcode: 8450
    streetname: Oudekreekweg
    streetnumber: <masked number for privacy reasons, you can choose 1-50>
    upcomingsensor: 1
    dateformat: "%d-%m-%Y"
    dateonly: 1
    dateobject: 0
    nameprefix: 1
    builtinicons: 0
    disableicons: 0
    dutch: 1

**Comment by pippyn** [comment]
This config is working fine for me on v4.7.20

**Comment by jeroomdm** [comment]
Not sure what happend but it's working again.
I'm on hassio 2021.5.0b5 now
