### ISSUE TITLE
Sensor values go to the value unknown after some time

### ISSUE THREAD

**Issue by arjanvroege** [pippyn/Home-Assistant-Sensor-Afvalbeheer#247]
After some time the values of the sensor go to a unknown state. The only solution is to restart HA and this fixes the issue for some time. I found the following error in the HA log, unsure if it relates to the issue:

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:629
Integration: afvalbeheer (documentation)
First occurred: 8:49:55 AM (1 occurrences)
Last logged: 8:49:55 AM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 438, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 667, in update
    r = await self.hass.async_add_executor_job(self.__get_data)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 629, in __get_data
    if session_cookie:
UnboundLocalError: local variable 'session_cookie' referenced before assignment

**Comment by arjanvroege** [comment]
The issue looks indeed solved. Have not seen the issue after updating.
