### ISSUE TITLE
Error after last update: Task exception was never retrieved

### ISSUE THREAD

**Issue by mikeo999** [pippyn/Home-Assistant-Sensor-Afvalbeheer#252]
Just upgraded to version v4.7.28

Was using is for a few day's and was working fine.
Saw an update and after the update i restart HA.
Now afvalbeheer is removed from Lovelace and needs to install Afvalbeheer again. 

Restart HA again after install but there is no afvalbeheer card found anymore, also CTRL-F5 is not resolving that.

wastecollector: Alkmaar
Postcode: 1486 MK

Logfile is giving me an error

`This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:958
Integration: afvalbeheer (documentation)
First occurred: 3:52:01 PM (1 occurrences)
Last logged: 3:52:01 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/afvalbeheer/sensor.py", line 455, in async_update
    await self.collector.update()
  File "/config/custom_components/afvalbeheer/sensor.py", line 986, in update
    await self.hass.async_add_executor_job(self.__fetch_address)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 958, in __fetch_address
    response = requests.get(
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/local/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**Comment by pippyn** [comment]
Thank you for reporting this bug.
This is fixed in v4.7.29

**Comment by mikeo999** [comment]
> 
> 
> Can you confirm this issue is fixed? Can we close this issue?

Sorry totally forgot to report back.
Yes the problem is solved with this update.
