### ISSUE TITLE
Circulus-Berkel URL change

### ISSUE THREAD

**Issue by roynijkamp** [pippyn/Home-Assistant-Sensor-Afvalbeheer#278]
Recently Circulus Berkel announced that they are going to change the name of the company into Circulus.
Today i noticed that the Waste sensors was not updated.

I found out that it has to do with the Circulus Berkel main URL in the senor.py
On line 646 i changed ` self.main_url = "https://mijn.circulus-berkel.nl"`
into ` self.main_url = "https://mijn.circulus.nl"` and everything works again.

**Comment by pippyn** [comment]
Thanks! I'll add this to the next release.

**Comment by DimitriTeerink** [comment]
> Recently Circulus Berkel announced that they are going to change the name of the company into Circulus. Today i noticed that the Waste sensors was not updated.
> 
> I found out that it has to do with the Circulus Berkel main URL in the senor.py On line 646 i changed ` self.main_url = "https://mijn.circulus-berkel.nl"` into ` self.main_url = "https://mijn.circulus.nl"` and everything works again.

Thanks, I can confirm this is working.

**Comment by pippyn** [comment]
Added in v4.9.0

Also added a warning to change `circulus-berkel` to `circulus` in your config

**Comment by jsimonetti** [comment]
I am not entirely sure what my problem is, but after upgrading to 4.9.0 I still get this error in my logs:
```
This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/afvalbeheer/sensor.py:670 
Integration: afvalbeheer (documentation) 
First occurred: 2:13:16 PM (1 occurrences) 
Last logged: 2:13:16 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/var/lib/hass/custom_components/afvalbeheer/sensor.py", line 464, in async_update
    await self.collector.update()
  File "/var/lib/hass/custom_components/afvalbeheer/sensor.py", line 706, in update
    r = await self.hass.async_add_executor_job(self.__get_data)
  File "/nix/store/rppr9s436950i1dlzknbmz40m2xqqnxc-python3-3.9.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/var/lib/hass/custom_components/afvalbeheer/sensor.py", line 670, in __get_data
    json_response_data = r.json()
  File "/nix/store/47w9wdpsz6arsd5zf7sic5d4sj7y5gkr-python3.9-requests-2.26.0/lib/python3.9/site-packages/requests/models.py", line 910, in json
    return complexjson.loads(self.text, **kwargs)
  File "/nix/store/dy4k7a0amd074i80zaa87fc071wadi5f-python3.9-simplejson-3.17.6/lib/python3.9/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/nix/store/dy4k7a0amd074i80zaa87fc071wadi5f-python3.9-simplejson-3.17.6/lib/python3.9/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/nix/store/dy4k7a0amd074i80zaa87fc071wadi5f-python3.9-simplejson-3.17.6/lib/python3.9/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any ideas how to troubleshoot this? It was working before with 4.8.1 (until they changed their URL).
