### ISSUE TITLE
no integration found when asked for restarting!

### ISSUE THREAD

**Issue by krikkel** [pippyn/Home-Assistant-Sensor-Afvalbeheer#313]
Does anyone have a clue what is going on?

Had afvalbeheer since a half year installed on previous installs on my Home Assistant,
worked perfectly!

Today I want to install it through HACS and the files are in my custom_components folder,
added my sensors in configuration.yaml
but got the next error.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:679
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 22:52:30 (1 occurrences)
Last logged: 22:52:30

[547149692544] The system cannot restart because the configuration is not valid: Platform error sensor.afvalbeheer - Integration 'afvalbeheer' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 189, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1627, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1664, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 679, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error sensor.afvalbeheer - Integration 'afvalbeheer' not found.

Home Assistant is the latest version
Versie | core-2022.5.3
-- | --
Type installatie | Home Assistant OS
Ontwikkeling | false
Supervisor | true
Docker | true
Gebruiker | root
Virtuele omgeving | false
Python-versie | 3.9.9
Besturingssysteem | Linux
Versie van het besturingssysteem | 5.10.103-v8
CPU-architectuur | aarch64
Tijdzone | Europe/Brussels

**Comment by pippyn** [comment]
Once you've installed the sensor through HACS, you'll have to first restart HA! Then add the config and restart again.

So please remove (or comment out) the sensor config and restart HA

**Comment by pippyn** [comment]
Closing stale issue
