### ISSUE TITLE
error na update: list index out of range

### ISSUE THREAD

**Issue by conradhagemans** [pippyn/Home-Assistant-Sensor-Afvalbeheer#387]
Vandaag de update gedraaid. krijg nu de volgende fout:

Update for sensor.rmn_first_upcoming fails
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 541, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 739, in async_device_update
    raise exc
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/afvalbeheer/sensor.py", line 298, in update
    collections = self.data.collections.get_first_upcoming()
  File "/config/custom_components/afvalbeheer/API.py", line 50, in get_first_upcoming
    first_item = upcoming[0]
IndexError: list index out of range

**Comment by pippyn** [comment]
See issue #382
