### ISSUE TITLE
Setup in latest release fails

### ISSUE THREAD

**Issue by myTselection** [pippyn/Home-Assistant-Sensor-Afvalbeheer#503]
File "/config/custom_components/afvalbeheer/API.py", line 1365, in _format_id
    return waste_collector + "-" + postcode + "-" + str(house_number)
           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by pippyn** [comment]
What is your config?

**Comment by Gunthervc** [comment]
After update!

Error during setup of component afvalbeheer
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 416, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/__init__.py", line 86, in async_setup
    data = get_wastedata_from_config(hass, conf)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/API.py", line 1318, in get_wastedata_from_config
    config["id"] = _format_id(waste_collector, postcode, street_number)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/afvalbeheer/API.py", line 1365, in _format_id
    return waste_collector + "-" + postcode + "-" + str(house_number)
           ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
TypeError: can only concatenate str (not "int") to str

**Comment by Jacob-nr5** [comment]
Still same error with V5.3.9

**Comment by Gunthervc** [comment]
5.3.9 solved it for me. Thanks

**Comment by myTselection** [comment]
5.3.9 fixed it for me too, thanks for the quick fix!
